name: Create InVEST Release DOI

on:
    workflow_dispatch:
        inputs:
            version:
                description: The InVEST version for which we're creating a DOI.
                required: true
                type: string
            datacite_instance:
                description: The target DataCite Fabrica instance.
                required: true
                default: 'test'
                options:
                    - test
                    - production
            publish:
                description: If checked, DOI will be published and immutable.  Metadata is always mutable.
                required: false
                type: boolean

permissions:
    contents: write

concurrency:
    cancel-in-progress: false
    group: ${{ github.workflow }}-${{ github.ref }}

jobs:
    execute:
        runs-on: ubuntu-latest
        env:
            NEW_DATACITE_FILE: invest-releases/${{ env.VERSION }}/datacite.json
            NEW_HTML_FILE: html/${{ env.VERSION }}.html
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Set up python
              uses: actions/setup-python@v6
              with:
                  python-version: 3.12
            - name: Install dependencies
              run: pip install -r requirements.txt
            #- name: Create new files in repo but don't overwrite
            #   # Assume that if files already exist, they've been manually edited and should continue to be manually edited.
            - name: Commit new changes
              run: |
                  git add "$NEW_DATACITE_FILE" "$NEW_HTML_FILE" "html/index.html"
                  git commit -m "GHA: Adding new files for version ${{ env.VERSION }}"
            - name: Push changes
              run: git push origin main
            - name: Create the DOI on DataCite
              run: |
                  if [[ ${{ inputs.publish }} ]]
                  then
                    # Using --publish will register the DOI and also make it
                    # findable.  See https://support.datacite.org/docs/doi-states for DOI
                    # states and allowed actions.
                    PUBLISH="--publish"
                  fi
                  if [[ "${{ inputs.datacite_instance }}" = "test" ]]
                  then
                    INSTANCE="--test"
                  fi
                  python register-doi.py $INSTANCE $PUBLISH $NEW_DATACITE_FILE
